In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = "PERM_data/PERM_Disclosure_Data_FY2023_Q4.xlsx"
# file_path = "/home/henli/avacacode/f1hub/PERM_Disclosure_Data_FY2023_Q4.csv"


df = pd.read_excel(file_path)

# Read the CSV file into a DataFrame
# df = pd.read_csv(file_path)


# Display the first few rows of the DataFrame
print(df.head())

df.desc

     CASE_NUMBER        CASE_STATUS RECEIVED_DATE DECISION_DATE REFILE  \
0  A-22262-24149          Withdrawn    2022-10-02    2022-10-02      N
1  A-21187-12839  Certified-Expired    2022-02-03    2022-10-03      N
2  A-21327-77110             Denied    2021-11-30    2022-10-03      N
3  A-21342-83195  Certified-Expired    2022-02-03    2022-10-03      N
4  A-21349-86725  Certified-Expired    2022-02-03    2022-10-03      N

  ORIG_FILE_DATE PREVIOUS_SWA_CASE_NUMBER_STATE SCHD_A_SHEEPHERDER  \
0            NaT                            NaN                  N
1            NaT                            NaN                  N
2            NaT                            NaN                  N
3            NaT                            NaN                  N
4            NaT                            NaN                  N

                EMPLOYER_NAME       EMPLOYER_ADDRESS_1  ...  \
0     Westgate Shellworld Inc      7012 Muncipal Drive  ...
1                  NIKE, INC.       ONE BOWERMAN DRIVE  ...
2     RIVERY TECHNOLOGIES INC           500 7TH AVENUE  ...
3                   ESRI INC.         380 NEW YORK ST.  ...
4  INGURAN LLC DBA STGENETICS  22575 STATE HWY 6 SOUTH  ...

  FOREIGN_WORKER_ALT_OCC_EXP FOREIGN_WORKER_EXP_WITH_EMPL  \
0                        NaN                          NaN
1                          Y                            N
2                          Y                            N
3                          Y                            N
4                        NaN                            N

  FOREIGN_WORKER_EMPL_PAY_FOR_ED FOREIGN_WORKER_CURR_EMPLOYED  \
0                              N                            N
1                              N                            Y
2                              N                            Y
3                              N                            Y
4                              N                            Y

  EMPLOYER_COMPLETED_APPLICATION               PREPARER_NAME  \
0                              N         FRANCES  DELAFUENTE
1                              N                   Chad T Li
2                              N           Rakhel S Milstein
3                              N             Jessica L Cross
4                              N  Beatriz  Trillos Ballerini

       PREPARER_TITLE              PREPARER_EMAIL  EMP_INFO_DECL_NAME  \
0            ATTORNEY          MICHELLE@DLGPA.COM        SAMIA  AHMED
1  Associate Attorney             chad.li@BAL.com     Diana  Loveless
2            Attorney          rsm@milsteinlg.com           Aviv  Noy
3            Attorney  jessica.cross@ogletree.com       Vinesh  Patel
4            Attorney            perm@tbvisas.com    Steven  Sfamenos

                   EMP_DECL_TITLE
0                           OWNER
1  Immigration Program Consultant
2                       CoFounder
3     Global Mobility Coordinator
4        Human Resources Director

[5 rows x 154 columns]

In [19]:
df["EMPLOYER_NAME"].nunique()

23836

In [20]:
df["AGENT_ATTORNEY_FIRM_NAME"].nunique()

5077

In [21]:
df["AGENT_ATTORNEY_NAME"].nunique()

6836

In [24]:
df.groupby("CLASS_OF_ADMISSION").nunique().sort_values(["CASE_NUMBER"])

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,REFILE,ORIG_FILE_DATE,PREVIOUS_SWA_CASE_NUMBER_STATE,SCHD_A_SHEEPHERDER,EMPLOYER_NAME,EMPLOYER_ADDRESS_1,...,FOREIGN_WORKER_ALT_OCC_EXP,FOREIGN_WORKER_EXP_WITH_EMPL,FOREIGN_WORKER_EMPL_PAY_FOR_ED,FOREIGN_WORKER_CURR_EMPLOYED,EMPLOYER_COMPLETED_APPLICATION,PREPARER_NAME,PREPARER_TITLE,PREPARER_EMAIL,EMP_INFO_DECL_NAME,EMP_DECL_TITLE
CLASS_OF_ADMISSION,,,,,,,,,,,,,,,,,,,,,
A-3,1,1,1,1,1,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
V-1,1,1,1,1,1,0,0,1,1,1,...,0,0,1,1,1,1,1,1,1,1
T-3,1,1,1,1,1,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
T-2,1,1,1,1,1,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
C-2,1,1,1,1,1,0,0,1,1,1,...,1,1,1,1,1,1,0,0,1,1
T-1,1,1,1,1,1,0,0,1,1,1,...,0,1,1,1,1,1,0,0,1,1
K-2,1,1,1,1,1,0,0,1,1,1,...,1,1,1,1,1,1,1,1,1,1
P-2,1,1,1,1,1,0,0,1,1,1,...,0,1,1,1,1,1,1,1,1,1
C-3,2,2,2,2,1,0,0,1,2,2,...,1,2,1,1,2,2,1,1,2,2
K-1,3,2,2,3,1,0,0,1,3,3,...,1,2,1,2,2,3,2,2,3,3
P-4,3,2,3,3,1,0,0,1,3,3,...,0,1,1,2,1,3,3,3,3,3
G-1,3,2,3,3,1,0,0,1,3,3,...,1,1,1,1,2,2,1,1,3,3
VWB,4,3,4,4,1,0,0,1,4,4,...,2,1,1,2,2,4,2,3,4,4
G-5,4,2,4,4,1,0,0,1,4,4,...,1,1,1,2,1,4,4,4,4,3
O-2,4,3,3,4,1,0,0,1,3,3,...,1,1,1,1,1,3,3,4,3,3
N,4,2,4,4,1,0,0,1,4,4,...,1,2,1,2,1,4,3,4,4,4
P-3,5,3,5,4,1,0,0,1,5,5,...,1,2,1,2,2,5,1,4,5,5
H-3,5,4,5,5,1,0,0,1,5,5,...,0,1,1,2,2,5,2,4,5,5
R-2,6,3,5,6,1,0,0,1,6,6,...,0,1,1,2,1,6,3,6,6,4
TD,8,4,8,8,1,0,0,1,8,8,...,1,1,1,2,2,7,4,6,8,8
O-3,8,3,8,8,1,0,0,1,8,8,...,1,1,1,2,2,5,2,4,8,7
H-1A,9,2,9,9,1,0,0,1,9,9,...,1,1,1,2,2,9,5,8,9,6
VWT,11,3,11,11,1,0,0,1,11,11,...,1,1,1,2,2,10,5,9,11,6
C-1,13,4,12,12,1,0,0,1,10,10,...,1,1,1,2,1,7,4,7,10,8
I,18,4,17,17,1,0,0,1,17,17,...,1,1,1,2,2,13,5,12,17,10
M-1,26,4,23,23,1,0,0,1,22,22,...,2,1,1,1,2,16,4,14,22,15
G-4,30,4,30,28,1,0,0,1,30,30,...,1,1,1,2,1,30,11,30,30,27
R-1,31,4,27,29,1,0,0,1,30,30,...,1,1,1,2,2,22,6,19,31,18
CW-1,32,3,20,24,1,0,0,1,16,16,...,1,2,1,2,2,5,5,4,17,12
P-1,34,4,32,32,1,0,0,1,31,31,...,2,1,1,2,2,27,7,23,31,25
A1/A2,53,4,43,45,1,0,0,1,45,45,...,2,2,1,2,2,27,7,28,45,26
J-2,67,4,59,56,1,0,0,1,62,60,...,2,2,1,2,2,60,20,59,60,48
H-1B1,74,4,65,59,1,0,0,1,59,56,...,2,2,2,2,2,59,21,53,62,56
Parolee,84,4,72,71,1,0,0,1,68,68,...,2,2,1,2,2,57,11,54,70,51
E-1,86,4,72,66,2,1,1,1,72,70,...,2,2,2,2,2,65,15,65,72,48
EWI,91,4,77,73,2,1,1,1,89,89,...,2,2,1,2,2,68,13,66,89,38
L-2,122,4,96,94,1,0,0,1,89,87,...,2,1,1,2,2,102,19,89,95,72
TPS,136,4,100,98,1,0,0,1,105,105,...,2,2,1,2,2,79,22,77,107,68
B-1,239,4,149,127,2,1,1,1,140,139,...,2,2,2,2,2,99,22,97,143,73
E-3,280,4,156,162,1,0,0,1,191,188,...,2,2,2,2,2,202,39,176,206,169
H-2A,289,4,140,124,2,1,1,1,161,160,...,2,2,2,2,2,90,21,88,168,50
O-1,316,4,191,175,1,0,0,1,230,228,...,2,2,1,2,2,226,37,206,239,170
H-4,357,4,194,178,1,0,0,1,225,221,...,2,2,1,2,2,222,33,205,237,164
F-2,427,4,221,188,1,0,0,1,274,271,...,2,1,1,2,2,162,27,158,269,101
J-1,456,4,240,194,2,1,1,1,365,362,...,2,2,2,2,2,238,36,239,362,169
H-2B,980,4,197,172,2,1,1,1,211,209,...,2,2,2,2,2,126,31,128,224,72
E-2,993,4,338,234,2,3,4,1,847,842,...,2,2,2,2,2,538,55,529,860,310
B-2,1593,4,397,249,2,2,2,1,1053,1047,...,2,2,2,2,2,496,68,497,1057,280
TN,1729,4,357,248,1,0,0,1,928,912,...,2,2,2,2,2,784,78,723,971,563
L-1,5222,4,429,252,1,0,0,1,1444,1347,...,2,2,2,2,2,1186,117,1094,1666,1155
Not in USA,9191,4,536,262,2,2,2,1,1423,1406,...,2,2,2,2,2,778,98,744,1523,532
F-1,10020,4,663,266,2,1,1,1,3279,3240,...,2,2,2,2,2,1770,142,1665,3411,1041
H-1B,70654,4,952,283,2,28,22,1,12552,11772,...,2,2,2,2,2,4670,365,4434,14734,6180

In [28]:
cols2keep = [
"CASE_NUMBER",
"CASE_STATUS",
"RECEIVED_DATE",
"DECISION_DATE",
"EMPLOYER_NAME",
"AGENT_ATTORNEY_FIRM_NAME",
"AGENT_ATTORNEY_NAME", 
"PW_TRACK_NUMBER",
"PW_SOC_TITLE",
"PW_SKILL_LEVEL",
"PW_WAGE",
"PW_SOC_CODE",
"PW_UNIT_OF_PAY",
"PW_WAGE_SOURCE",
"PW_SOURCE_NAME_OTHER",
"PW_DETERMINATION_DATE",
"PW_EXPIRATION_DATE",
"WAGE_OFFER_FROM",
"WAGE_OFFER_TO",
"WAGE_OFFER_UNIT_OF_PAY",
"JOB_TITLE",
"MINIMUM_EDUCATION",
"JOB_EDUCATION_MIN_OTHER",
"MAJOR_FIELD_OF_STUDY",
"REQUIRED_TRAINING",
"REQUIRED_TRAINING_MONTHS",
"REQUIRED_FIELD_OF_TRAINING",
"REQUIRED_EXPERIENCE",
"REQUIRED_EXPERIENCE_MONTHS",
"COUNTRY_OF_CITIZENSHIP",
"CLASS_OF_ADMISSION",
"FOREIGN_WORKER_EDUCATION",
"FOREIGN_WORKER_EDUCATION_OTHER",
"FOREIGN_WORKER_INFO_MAJOR",
"FOREIGN_WORKER_INST_OF_ED",
"FOREIGN_WORKER_ED_INST_COUNTRY"]

In [29]:
filtereddf = df[cols2keep]

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,EMPLOYER_NAME,AGENT_ATTORNEY_FIRM_NAME,AGENT_ATTORNEY_NAME,PW_TRACK_NUMBER,PW_SOC_TITLE,PW_SKILL_LEVEL,...,REQUIRED_FIELD_OF_TRAINING,REQUIRED_EXPERIENCE,REQUIRED_EXPERIENCE_MONTHS,COUNTRY_OF_CITIZENSHIP,CLASS_OF_ADMISSION,FOREIGN_WORKER_EDUCATION,FOREIGN_WORKER_EDUCATION_OTHER,FOREIGN_WORKER_INFO_MAJOR,FOREIGN_WORKER_INST_OF_ED,FOREIGN_WORKER_ED_INST_COUNTRY
0,A-22262-24149,Withdrawn,2022-10-02,2022-10-02,Westgate Shellworld Inc,DELAFUENTE LAW LLC,FRANCES DELAFUENTE,P10021356781640,RETAIL SALESPERSONS,Level I,...,NaN,N,NaN,NICARAGUA,NaN,High School,NaN,HIGH SCHOOL DIPLOMA,INSTITUTO PUBLICO DE YALAGUINA,NICARAGUA
1,A-21187-12839,Certified-Expired,2022-02-03,2022-10-03,"NIKE, INC.",Berry Appleman Leiden LLP,Chad T Li,P10021127296744,Marketing Managers,Level IV,...,NaN,Y,36.0,THAILAND,L-1,Master's,NaN,BUSINESS ADMINISTRATION,SIAM UNIVERSITY,THAILAND
2,A-21327-77110,Denied,2021-11-30,2022-10-03,RIVERY TECHNOLOGIES INC,Milstein Law Group PLLC,Rakhel S Milstein,P10021025032043,Chief Executive Officer,Level IV,...,NaN,N,NaN,ISRAEL,E-2,Bachelor's,NaN,INFORMATION SYSTEMS ENGINEERING,BEN GURION UNIVERSITY OF THE NEGEV,ISRAEL
3,A-21342-83195,Certified-Expired,2022-02-03,2022-10-03,ESRI INC.,"Ogletree, Deakins, Nash, Smoak Stewart, PC",Jessica L Cross,P10021137319941,Marketing Managers,Level III,...,NaN,Y,36.0,CANADA,H-1B,Master's,NaN,CIVIL ENGINEERING,RYERSON UNIVERSITY,CANADA
4,A-21349-86725,Certified-Expired,2022-02-03,2022-10-03,INGURAN LLC DBA STGENETICS,"Trillos Ballerini Law Firm, P.C.",Beatriz Trillos Ballerini,P10021040066303,Marketing Managers,Level IV,...,NaN,Y,60.0,UNITED KINGDOM,Not in USA,Master's,NaN,BUSINESS ADMINISTRATION,UNIVERSITY OF BIRMINGHAM,UNITED KINGDOM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116422,A-23144-46945,Withdrawn,2023-05-24,2023-09-29,WL Nails Inc,Vietnamese Business Immigration Services PLLC,Tan T Bui,P10022069966387,Manicurists and Pedicurists,Level I,...,NaN,N,NaN,VIETNAM,L-2,NaN,NaN,NaN,NaN,NaN
116423,A-23144-46992,Withdrawn,2023-05-24,2023-09-29,WL Nails Inc,Vietnamese Business Immigration Services PLLC,Tan T Bui,P10022069966387,Manicurists and Pedicurists,Level I,...,NaN,N,NaN,VIETNAM,Not in USA,NaN,NaN,NaN,NaN,NaN
116424,A-23144-46995,Withdrawn,2023-05-24,2023-09-29,WL Nails Inc,Vietnamese Business Immigration Services PLLC,Tan T Bui,P10022069966387,Manicurists and Pedicurists,Level I,...,NaN,N,NaN,VIETNAM,Not in USA,NaN,NaN,NaN,NaN,NaN
116425,A-23144-46997,Withdrawn,2023-05-24,2023-09-29,WL Nails Inc,Vietnamese Business Immigration Services PLLC,Tan T Bui,P10022069966387,Manicurists and Pedicurists,Level I,...,NaN,N,NaN,VIETNAM,Not in USA,NaN,NaN,NaN,NaN,NaN
116426,A-23144-46999,Withdrawn,2023-05-24,2023-09-29,WL Nails Inc,Vietnamese Business Immigration Services PLLC,Tan T Bui,P10022069966387,Manicurists and Pedicurists,Level I,...,NaN,N,NaN,VIETNAM,Not in USA,NaN,NaN,NaN,NaN,NaN

In [37]:
filtereddf = df[cols2keep]

In [31]:
import sqlite3

In [39]:
conn = sqlite3.connect("perm.db")

In [40]:
filtereddf.to_sql("y2023", conn, if_exists="replace", index=False) 
conn.close()

In [41]:
filtereddf.describe()

,RECEIVED_DATE,DECISION_DATE,PW_WAGE,PW_DETERMINATION_DATE,PW_EXPIRATION_DATE,WAGE_OFFER_FROM,WAGE_OFFER_TO,REQUIRED_TRAINING_MONTHS,REQUIRED_EXPERIENCE_MONTHS
count,116427,116427,1.164060e+05,116357,116345,1.164250e+05,4.533100e+04,1153.000000,61365.000000
mean,2022-06-09 05:54:18.821407232,2023-04-06 15:09:07.759540480,9.049774e+04,2022-01-04 21:37:01.408252160,2022-07-18 16:25:03.555804160,1.024635e+05,1.693874e+05,25.888985,30.197963
min,2007-11-20 00:00:00,2022-10-02 00:00:00,7.250000e+00,2000-07-09 00:00:00,1930-03-22 00:00:00,7.500000e+00,0.000000e+00,0.000000,0.000000
25%,2022-03-29 00:00:00,2023-01-10 00:00:00,5.393400e+04,2021-10-07 00:00:00,2022-06-30 00:00:00,5.971700e+04,1.337230e+05,3.000000,12.000000
50%,2022-06-21 00:00:00,2023-04-06 00:00:00,9.555500e+04,2022-01-11 00:00:00,2022-06-30 00:00:00,1.071630e+05,1.692000e+05,24.000000,24.000000
75%,2022-09-01 00:00:00,2023-07-05 00:00:00,1.209520e+05,2022-04-12 00:00:00,2022-07-11 00:00:00,1.400000e+05,2.080000e+05,36.000000,36.000000
max,2023-05-31 00:00:00,2023-09-29 00:00:00,3.802200e+06,2025-02-04 00:00:00,2028-03-01 00:00:00,6.524999e+06,3.802200e+06,120.000000,240.000000
std,NaN,NaN,4.703117e+04,NaN,NaN,6.384576e+04,7.588311e+04,21.937169,22.306522